name: AI Agent for software testing
run-name: >
  ${{ 
    github.event.client_payload.testCase.userStoryId && github.event.client_payload.testCase.testCaseId 
      && format('{0} - {1}, {2}', github.event.client_payload.testCase.userStoryId, github.event.client_payload.testCase.testCaseId, github.event.action) 
    || format('{0}, {1}', github.event.client_payload.suite.name, github.event.action) 
  }}

on:
  repository_dispatch:
    types: [agent, crawl]

jobs:
  test:
    name: ${{ github.event.action}}
    runs-on: self-hosted

    steps:
      - uses: Wopee-io-DEV/run-agent@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WOPEE_API_KEY: ${{ secrets.WOPEE_API_KEY }}
          WOPEE_API_URL: ${{ vars.WOPEE_API_URL || 'https://api.wopee.io' }}
          WOPEE_PROJECT_UUID: ${{ vars.WOPEE_PROJECT_UUID }}
          WOPEE_PROJECT_URL: ${{ vars.WOPEE_PROJECT_URL || 'https://dronjo.wopee.io' }}
          WOPEE_SCREENSHOT_VALIDATION_ENABLED: "true"
          WOPEE_BRANCH_NAME: master
          WOPEE_CI_BUILD_ID: build-123
          WOPEE_CUSTOM_TAGS: custom-tag
          WOPEE_ENABLE_SOFT_ASSERT: "true"
          WOPEE_PIXEL_TO_PIXEL_DIFF_TOLERANCE: "0.1"
          WOPEE_COLLECT_PAGE_CONTENT: "true"
          # WOPEE_AGENT_AUTO_UPDATE: "true"
          BASIC_AUTH_USER: ${{ secrets.BASIC_AUTH_USER }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
